
AWL_MODEL: # element recognition model -- logo only
  CFG_PATH: CONDA_ENV_PATH_PLACEHOLDER/lib/python3.8/site-packages/phishintention/src/AWL_detector_utils/configs/faster_rcnn_web.yaml # os.path.join(os.path.dirname(__file__), xxx)
  WEIGHTS_PATH: models/model_final.pth

CRP_CLASSIFIER:
  WEIGHTS_PATH: models/BiT-M-R50x1V2_0.005.pth.tar
  MODEL_TYPE: 'mixed'

CRP_LOCATOR: # element recognition model -- logo only
  CFG_PATH: CONDA_ENV_PATH_PLACEHOLDER/lib/python3.8/site-packages/phishintention/src/crp_locator_utils/login_finder/configs/faster_rcnn_login_lr0.001_finetune.yaml # os.path.join(os.path.dirname(__file__), xxx)
  WEIGHTS_PATH: CONDA_ENV_PATH_PLACEHOLDER/lib/python3.8/site-packages/phishintention/src/crp_locator_utils/login_finder/output/lr0.001_finetune/model_final.pth

SIAMESE_MODEL: # extended 277
  NUM_CLASSES: 277 # number of brands, users don't need to modify this even the targetlist is expanded
  WEIGHTS_PATH: models/bit_new.pth.tar
  OCR_WEIGHTS_PATH: models/demo.pth.tar
  TARGETLIST_PATH: '../../data/targetlist/expand277_new'
  MATCH_THRE: 0.83 # FIXME: threshold is 0.87 in phish-discovery?
  DOMAIN_MAP_PATH: 'models/domain_map.pkl'

# SIAMESE_MODEL: # brand 277
#   NUM_CLASSES: 277 # number of brands, users don't need to modify this even the targetlist is expanded
#   WEIGHTS_PATH: ../reproduce_phishintention/trained_models/bit.pth.tar
#   OCR_WEIGHTS_PATH: ../reproduce_phishintention/trained_models/demo.pth.tar
#   TARGETLIST_PATH: '../../data/targetlist/expand277'
#   MATCH_THRE: 0.83 # FIXME: threshold is 0.87 in phish-discovery?
#   DOMAIN_MAP_PATH: '../reproduce_phishintention/trained_models/domain_map.pkl'
